[workspace]
members = [
    "toshi-server",
    "toshi-proto",
    "toshi-client",
    "toshi-types",
    "toshi-raft"
]

[profile.dev.package."*"]
opt-level = 2

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
lto = true
rpath = false
codegen-units = 1
